// File generated by hand from android/app/google-services.json (Firebase
// project `cachy-057`). Mirrors what `flutterfire configure` would emit, but
// only Android is configured — the other platforms have no registered Firebase
// app yet. To enable web (for `flutter run -d chrome`) or iOS, register those
// apps in the Firebase console and re-run `flutterfire configure`, which will
// overwrite this file with real per-platform values.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'No Firebase web app is registered yet. Register one in the Firebase '
        'console and re-run `flutterfire configure` to enable web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '$defaultTargetPlatform. Only Android is set up — register the app '
          'in the Firebase console and re-run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsQvYezQpozLGZENB9gquVlYlNt5NBJo',
    appId: '1:65028456728:android:01daa0a9cb7a2b73ec9e6d',
    messagingSenderId: '65028456728',
    projectId: 'cachy-057',
    storageBucket: 'cachy-057.firebasestorage.app',
  );
}
