// File generated by hand from the Firebase console (project `cachy-057`):
// Android from google-services.json, web from the registered web app config.
// Mirrors what `flutterfire configure` would emit. iOS/macOS/Windows have no
// registered Firebase app yet — register them and re-run `flutterfire configure`
// to enable those platforms.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '$defaultTargetPlatform. Only Android and web are set up — register '
          'the app in the Firebase console and re-run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQsQvYezQpozLGZENB9gquVlYlNt5NBJo',
    appId: '1:65028456728:android:01daa0a9cb7a2b73ec9e6d',
    messagingSenderId: '65028456728',
    projectId: 'cachy-057',
    storageBucket: 'cachy-057.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDessB3eRZTk61Td9VCfeqR12M1AyDmdiQ',
    appId: '1:65028456728:web:f59afb5892da1d9cec9e6d',
    messagingSenderId: '65028456728',
    projectId: 'cachy-057',
    authDomain: 'cachy-057.firebaseapp.com',
    storageBucket: 'cachy-057.firebasestorage.app',
    measurementId: 'G-NBY51G71WC',
  );
}
